### ISSUE TITLE
Configuring Azure Application Insight in Taurus Tasks

### ISSUE THREAD

**Issue by goyalg8** [algattik/azure-pipelines-jmeter-extension#10]
Can you please clarify the following sentences as you mentioned in the Jmeter MArketplace extension. 

In your pipeline, configure the JMeter Installer task, the Taurus Installer task, and the Taurus Runner task. As argument to the Taurus Runner task, enter:

-o modules.jmeter.properties.INSTRUMENTATION_KEY="<your key>" your-test-file.jmx

Should I configure all tasks or just Taurus Runner task as Taurus Argument field to include -o modules.jmeter.properties.INSTRUMENTATION_KEY="<your key>" your-test-file.jmx

All other tasks except Taurus run task does not show any argument field. Can you please make it more clear.
Thank you

**Comment by algattik** [comment]
Clarified documentation
