### ISSUE TITLE
Taurus Runner task does not complete on windows-latest vm when there are multiple scenarios

### ISSUE THREAD

**Issue by tribalsarthur** [algattik/azure-pipelines-jmeter-extension#13]
When the taurus config includes multiple scenarios which run a jmeter jmx file, the generation of the report fails with the known error mentioned in the task source code:

```
An error occurred: Error while processing samples: Consumer failed with message :Consumer failed with message :Consumer failed with message :Consumer failed with message :Consumer failed with message :D:\a\1\s\temp\latencyVsRequest\latencyVsRequest3119647701290362307-0 does not exist or is not readable
errorlevel=1
```

On windows-latest agents, the task does not finish. It continues to run until the build times out or is cancelled.

If the build is cancelled, the following message is then displayed in the logs:

2021-05-25T09:43:05.7223729Z Press any key to continue . . . ^C

This does not happen on ubuntu-latest. It also has the error, but it completes and moves on to the next task in the build.

A possible fix might be not to generate the report unless the report name parameter is specified:

```
    if (reportName.trim()) {
        let reportDir = await runner.generateJMeterReport(jmeterPath, outputDir);
        await runner.uploadJMeterReport(reportDir, reportName);
    }
```
This would allow us to work around the problem as we are not providing that parameter, and seems neat because if its not being uploaded, it isn't necessary to generate it.

Side note - 
The report generation appears to fail because there are multiple kpi.jtl files (kpi.jtl, kpi-1.jtl) in the output folder when the report generation runs. 
Renaming one of the files so it doesn't have the same prefix as any other jtl files in the folder and generating the report correctly generates the file for that output.
Merging them into one file with a completely different name and generating the report for that output also works.

**Comment by algattik** [comment]
Bug is due to a `pause` command in the `jmeter.bat` file.
Implemented code workaround as suggested. Thank you!

**Comment by MegaBaobab** [comment]
Hello,
I'm currently trying to use the taurus runner task with several jmeter jmx file and i have the issue mentioned by @tribalsarthur during the report generation. I don't see how i can rename or merge the kpi.jtl files between the tests and the report generation as the task does both in a row. Is there a way to do it or is it not possible to generate report when runnig several files with the task ?
Thanks
