### ISSUE TITLE
cryptographic hash algorithms update required 

### ISSUE THREAD

**Issue by manimsd7** [algattik/azure-pipelines-jmeter-extension#17]
Hi @algattik  ,

We are looking to use this plugin for jMeter load testing from ADO pipelines.

After analysis of the source code our security team found weak cryptographic hash algorithms ( SHA1 ) is used in it. 

Could you please let know if any immediate plan to update the same in future patch releases.

If possible kindly share contact email so we can contact you directly

Cheers,
Mani

**Comment by algattik** [comment]
Updated extension (version 0.1.7) to use SHA-224. Thanks for reporting.
