### ISSUE TITLE
Error: The process 'C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\bzt.exe' failed with exit code 3221225477

### ISSUE THREAD

**Issue by stevenbowler** [algattik/azure-pipelines-jmeter-extension#22]
Please see attached images, and thanks.

![image](https://user-images.githubusercontent.com/56875138/157779493-12995758-029a-4023-84e9-14c0a7432e89.png)

![image](https://user-images.githubusercontent.com/56875138/157779704-6eb0c457-e7f2-45e1-814f-39bd87d5d14d.png)

**Comment by algattik** [comment]
I can reproduce the issue on Windows. In the meantime, switching to an Ubuntu agent should solve it

**Comment by stevenbowler** [comment]
ubuntu did it. thank you sir.
