### ISSUE TITLE
Dependency update concern

### ISSUE THREAD

**Issue by kstine** [algattik/azure-pipelines-jmeter-extension#33]
Are you planning on updating this Azure Plugin?

- version of jmeter 5.4.2 from 2021-12-16
- taurus (bzt==1.15.3) from date here and has a python dependency range of 3.7 to 3.9 (which has an EOL of 2025-10).
- On the Readme for the plugin it even mentions only using python 3.8(which has an EOL 2024-10) because of a reported bug

Or are you expecting to deprecate this azure plugin?

Thank you.

**Comment by algattik** [comment]
I've updated the defaults and documentation, and tested that the extension works on Python 3.9.

Note that the Taurus module is documented to support up to 3.9: https://pypi.org/project/bzt/
