### ISSUE TITLE
Two versions of plug-in

### ISSUE THREAD

**Issue by tomas199** [algattik/azure-pipelines-jmeter-extension#5]
Hello guys,
Could you please explain me what is difference between two versions of this plug-in currently available on marketplace.visualstudio? Description of both looks same, only difference I found at all is word "dev" in first link.

https://marketplace.visualstudio.com/items?itemName=AlexandreGattiker.jmeter-tasks-dev&ssr=false#overview
https://marketplace.visualstudio.com/items?itemName=AlexandreGattiker.jmeter-tasks&ssr=false#overview

**Comment by algattik** [comment]
Thanks for reporting - I've unpublished the first one.
