### ISSUE TITLE
Error installing the jmeter extension

### ISSUE THREAD

**Issue by DaveKLloyd** [algattik/azure-pipelines-jmeter-extension#6]
Are we missing something? We are getting this error when we try to use the install jmeter tool installer

**Error: Failed to download JMeter from url https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.2.1.zip. Error Error: self signed certificate in certificate chain**

Trying to install version 5.2.1 and 
Plugins is set to _jpgc-casutg,jpgc-dummy,jpgc-ffw,jpgc-fifo,jpgc-functions,jpgc-json,jpgc-perfmon,jpgc-prmctl,jpgc-tst_

This is on an on premise windows agent.

Thanks for any help

**Comment by drcjmeter** [comment]
Hello, I got the same error. Any update to this issue

**Comment by algattik** [comment]
Upgraded default version to 5.4.1
