### ISSUE TITLE
Azure DevOps Task TaurusInstaller installation is failing with error 

### ISSUE THREAD

**Issue by bhadana-rajesh** [algattik/azure-pipelines-jmeter-extension#8]
Hi, 

Environment : 
Azure DevOps, 
microsoft hosted ubuntu-18.04,  

Its fail to install TaurusInstaller, with error Command errored out with exit status 1: /opt/hostedtoolcache/Python/3.9.0/x64/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9z882prr/fuzzyset/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9z882prr/fuzzyset/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cmd10gpt/install-record.txt --single-version-externally-managed --compile --install-headers /opt/hostedtoolcache/Python/3.9.0/x64/include/python3.9/fuzzyset Check the logs for full command output.

 
Please see attached task logs

- task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'
      - task: JMeterInstaller@0
        inputs:
          jmeterVersion: '5.2.1'
      - task: TaurusInstaller@0
        inputs:
          taurusVersion: '1.14.1'
          pythonCommand: 'python3'

[TaurusInstallerLogs.log](https://github.com/algattik/azure-pipelines-jmeter-extension/files/5565786/TaurusInstallerLogs.log)

**Comment by algattik** [comment]
This is related to a third-party module, the cause of this is unclear:
```
 Running setup.py install for fuzzyset: started
2020-11-18T09:45:45.6242527Z     fuzzyset/cfuzzyset.c:6309:35: error: â€˜PyTypeObject {aka struct _typeobject}â€™ has no member named â€˜tp_printâ€™; did you mean â€˜tp_dictâ€™?
```
Maybe try with another version of Taurus, e.g. 1.15.1? https://gettaurus.org/docs/Changelog/
Or try `pip3 install fuzzyset`before TaurusInstaller?

**Comment by bhadana-rajesh** [comment]
Hi 

Thank you @algattik for quick response.

task: UsePythonVersion@0
inputs:
versionSpec: '3.x'
addToPath: true
architecture: 'x64'

I have change versionSpec from '3.x' to '3.8', and it start working again.

Thanks,
Rajesh

**Comment by algattik** [comment]
Updated documentation to mention that Python 3.9 is not supported
