### ISSUE TITLE
Fails to Install Cmdrunner.jar due to HTTP on Azure windows Box

### ISSUE THREAD

**Issue by sandeepModaboyina** [algattik/azure-pipelines-jmeter-extension#9]
Hi , 
Jemter Installer is failing to install on Internally hosted agent box . 
with the following error message :: 
![image](https://user-images.githubusercontent.com/26226408/106877561-cb998a00-66d0-11eb-99f9-f0ec77b5c459.png)

when we try to access the URL:   http://search.maven.org/remotecontent?filepath=kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar on Agent box we get below error message : 

![image](https://user-images.githubusercontent.com/26226408/106877366-94c37400-66d0-11eb-858a-e46b82cfe919.png)

if its HTTPS : the URL loads fine on the box 

is it possible to use HTTPS ?

**Comment by Willliamm** [comment]
The same here

**Comment by algattik** [comment]
Updated to use https
